import { Inter } from 'next/font/google'
import './globals.css'
import TanStackProvider from '@/providers/TanStackProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Js With Tailwind',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackProvider>
          {children}
        </TanStackProvider>
      </body>
    </html>
  )
}
